### ISSUE TITLE
images fail to load

### ISSUE THREAD

**Issue by ghost** [stormmurdoc/sent#1]
Hello! I cloned `sent` from [suckless software](https://git.suckless.org/sent), but it can't seem to handle images...

```
$ make
$ sudo make install
$ ls nyan.png sent
nyan.png  sent
$ sent <<< @nyan.png # should display nyan.png
sh: line 1: 2ff: command not found
sent: Unable to read filtered file 'nyan.png': No such file or directory
```

Any idea what could be causing the issue?

**Comment by GooseDeveloper** [comment]
Installing [`farbfield`](https://tools.suckless.org/farbfeld/) fixed the issue

**Comment by ghost** [comment]
Installing [`farbfield`](https://tools.suckless.org/farbfeld/) fixed the issue
